version: "3"

services:
  backend:
    build: ./
    container_name: bgd_cont
    working_dir: /board_game_django
    command:
      - ./commands/start_server.sh
    ports:
      - 8010:8008
    volumes:
      - ./src:/board_game_django/src
    env_file:
      - .env

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: { }
