version: "3"

services:
  backend:
    build: ./
    container_name: bgd_cont
    working_dir: /Board_Game_Django
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - static_content:/Board_Game_Django/src/static
      - media_content:/Board_Game_Django/src/media
      - ./src:/Board_Game_Django/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongo:
    image: mongo
    restart: always
    container_name: mongo_container
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_admin_container
    ports:
      - 8091:8081
    links:
      - mongo
    env_file:
      - .env
    depends_on:
      - mongo

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/Board_Game_Django/src/static
      - media_content:/Board_Game_Django/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend


volumes:
  pg_data: { }
  pgadmin_data: { }
  mongo_data: { }
  static_content: { }
  media_content: { }