# Generated by Django 4.1.3 on 2022-11-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="src/publishers/images"),
        ),
    ]
