# Generated by Django 4.1.3 on 2022-11-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board_game", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agecategory",
            options={"verbose_name_plural": "age categories"},
        ),
        migrations.AlterModelOptions(
            name="playercountcategory",
            options={"verbose_name_plural": "player counting"},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name_plural": "series"},
        ),
        migrations.AlterModelOptions(
            name="timecategory",
            options={"verbose_name_plural": "time categories"},
        ),
    ]
