# Generated by Django 4.1.3 on 2022-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_game", "0004_remove_order_order_id_alter_game_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="src/media/images"),
        ),
    ]
